version: "3"
services:
  web:
    container_name: server_web
    restart: always
    build: .
    ports:
    - "80:3001"
    links:
    - mongo
  mongo:
    container_name: mongo
    image: mongo:latest
    ports:
    - "27017:27017"
